### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Nohac** [granateio/granate#5]
## Generator

- [ ] Basic 
    - [x] go-graphql code
    - [ ] go interfaces
    - [x] go boilerplate 
- [ ] Advanced 
    - [x] Relay
    - [ ] Subscriptions
- [ ] Others
    - [x] Graphiql
    - [ ] File handling (upload)
    - [ ] Support more languages
    - [ ] Faker test interface implementations

## General TODOS

- [ ] Usage examples
- [ ] Write tests
- [ ] Documentation
- [ ] Make a proper README file
- [ ] Add many, many badges
